name: Discord Bot Deployment

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Kill all running instances
      run: |
        if killall -9 node; then
          echo "Found and terminated Node.js processes."
        else
          echo "No Node.js processes found."
        fi
      # Ignore exit code (always continue to the next step)
      continue-on-error: true
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Deploy bot
      run: |
        # Any additional deployment steps you need, e.g., restarting the bot
        npm start
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
