name: Discord Bot Deployment

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Kill the last running instance
      run: |
        # Define your GitHub Personal Access Token (PAT) with workflow permissions
        GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
        
        # Get the current workflow run ID
        WORKFLOW_RUN_ID=$(echo $GITHUB_RUN_ID)
        
        # Get the list of workflow runs for the current workflow and sort them by created_at
        RUNS=$(curl -s -X GET "https://api.github.com/repos/JHVIW/Secret-Santa-Bot/actions/runs" -H "Authorization: token $GITHUB_TOKEN" | jq -r '.workflow_runs | sort_by(.created_at) | .[] | .id')
        
        # Get the last run (which will be the most recent)
        LAST_RUN_ID=$(echo "$RUNS" | tail -n 1)
        
        # Cancel the last run if it's not the current run
        if [ "$LAST_RUN_ID" != "$WORKFLOW_RUN_ID" ]; then
          curl -s -X POST "https://api.github.com/repos/${{ github.repository }}/actions/runs/$LAST_RUN_ID/cancel" -H "Authorization: token $GITHUB_TOKEN"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Deploy bot
      run: |
        # Any additional deployment steps you need, e.g., restarting the bot
        npm start
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
